import Head from 'next/head'
import React from 'react'
import Content from '../components/contact/Content'
import Hero from '../components/contact/Hero'
import Copyright from '../components/index/Copyright'
import Footer from '../components/index/Footer'
import Navbar from '../components/index/Navbar'
import Contact from '../components/index/Contact'

function ContactPage() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <style>
          @import url('https://fonts.googleapis.com/css2?family=Alfa+Slab+One&display=swap');
        </style>
        <style>
          @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@700&display=swap');
        </style>
      </Head>

      <Navbar />
      <Hero />
      <Content />
      <Contact bg="#BE6361" textColor="white"/>
      <Footer />
      <Copyright />
    </div>
  )
}

export default ContactPage