import Head from 'next/head'
import Contacts from '../components/index/Offers'
import Content from '../components/index/Content'
import Hero from "../components/index/Hero"
import Navbar from "../components/index/Navbar"
import Ladder from '../components/index/Ladder'
import Gallery from '../components/index/Gallery'
import TrySection from '../components/index/TrySection'
import ShoppingCart from '../components/index/ShoppingCart'
import Subscription from '../components/index/Subscription'
import Form from '../components/index/Form'
import Footer from '../components/index/Footer'
import Copyright from '../components/index/Copyright'
import Contact from '../components/index/Contact'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <style>
          @import url('https://fonts.googleapis.com/css2?family=Alfa+Slab+One&display=swap');
        </style>
        <style>
          @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@700&display=swap');
        </style>
      </Head>

      <Navbar />
      <Hero />
      <Content />
      <Contacts />
      <Ladder />
      <Gallery />
      <TrySection />
      <ShoppingCart />
      <Subscription />
      <Form />
      <Contact />
      <Footer />
      <Copyright />
    </div>
  )
}
