import Head from 'next/head'
import Contacts from '../components/Offers'
import Content from '../components/Content'
import Hero from "../components/Hero"
import Navbar from "../components/Navbar"
import Ladder from '../components/Ladder'
import Test from '../components/Test'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Hero />
      <Content />
      <Contacts />
      <Ladder />
    </div>
  )
}
