import React from 'react'
import Navbar from "../components/index/Navbar"
import Head from "next/head"

function Portfolio() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />

                <style>
                    @import url('https://fonts.googleapis.com/css2?family=Alfa+Slab+One&display=swap');
                </style>
                <style>
                    @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@700&display=swap');
                </style>
            </Head>


            <Navbar />
        </div>
    )
}

export default Portfolio